# Generated by Django 4.1.7 on 2023-04-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angl', models.TextField(blank=True, null=True)),
                ('rus', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dict',
                'managed': True,
            },
        ),
    ]
