# Generated by Django 4.1.7 on 2023-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_maths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
