# Generated by Django 4.1.7 on 2023-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_maths', '0002_alter_dict_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_custom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('angl', models.TextField(blank=True, null=True)),
                ('rus', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dict_custom',
                'managed': True,
            },
        ),
    ]
