# Generated by Django 4.1.7 on 2023-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_maths', '0004_customs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customs',
            name='email',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customs',
            name='username',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
